apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-demo-service # Name of the service (leverage in ingress config)
  namespace: {{ .Values.Namespace }} # Namespace targeted for deployment
spec:
  ports:
    - protocol: {{ .Values.ports.protocol }}
      port: {{ .Values.ports.ingressPort }} # Port service is expecting incoming traffic
      targetPort: {{ .Values.ports.containerPort }} # Port the container is listening to
  sessionAffinity: ClientIP # Clients will maintain a connection to the pod they first hit for up to 3 hrs
  selector:
    app: {{ .Values.appName }} # Name defined in the Deployment
